FROM node:18-alpine

RUN mkdir -p /app/node_modules/.vite \
    && chown -R node:node /app/node_modules \
    && chown -R node:node /app/node_modules/.vite

COPY package*.json ./app

WORKDIR /app

RUN npm install

COPY . ./app

EXPOSE 5040

ENV NODE_ENV=development-docker

USER node

CMD ["npm", "start"]