version: "3.6"
### networks
networks:
  kanri-net:
    driver: bridge
###
services:
  projectkanri-db:
    image: mongo:latest
    container_name: projectkanri-db
    networks:
      - kanri-net
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=projectkanri
      - MONGO_INITDB_ROOT_PASSWORD=password123
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    container_name: api
    networks:
      - kanri-net
    volumes:
      - ./api:/app:rw
      - /app/node_modules
    ports:
      - 5051:5051
    environment:
      - PORT=5051
      - EMAIL_SECRET=secret2
      - SESS_SECRET=secret
      - NODE_ENV=development
      - MONGODB_URI=mongodb://projectkanri:password123@projectkanri-db
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_HOST=${MAIL_HOST}
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.development
    container_name: client
    networks:
      - kanri-net
    volumes:
      - ./client:/app:rw
      - /app/node_modules
    environment:
      - PORT=5050
      - NODE_ENV=development
      - VITE_APP_API_URL=http://localhost:5051
    ports:
      - 5050:5050 # you should keep these the same in local dev
 
volumes:
  db-data: