// PROJECT ACTIONS
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";

// TASK ACTIONS
export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";

// USER ACTIONS
export const UPDATE_USER = "UPDATE_USER";
